# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcessingData.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 688)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                       stop:0 rgba(24, 53, 107, 255),\n"
"                                       stop:0.25 rgba(94, 53, 107, 255),\n"
"                                       stop:0.5 rgba(24, 53, 107, 255),\n"
"                                       stop:0.75 rgba(25, 75, 75, 255),\n"
"                                       stop:1 rgba(24, 53, 107, 255));\n"
"    color:rgba(24, 53, 107, 255);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:1.2, \n"
"    fx:0.5, fy:0.5, \n"
"    stop:0 rgba(24, 53, 107, 255), stop:1 rgba(32, 86, 146, 255));\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    color: #ffffff;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 8px 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:1.2, \n"
"    fx:0.5, fy:0.5, \n"
"    stop:0 rgba(32, 86, 146, 255), stop:1 rgba(24, 53, 107, 255));\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgba(255, 255, 255, 0.3);\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    color: #a3a3a3;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(191, 171))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:1.2, \n"
"    fx:0.5, fy:0.5, \n"
"    stop:0 rgba(24, 53, 107, 255), stop:1 rgba(32, 86, 146, 255));\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    color: #ffffff;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 8px 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:1.2, \n"
"    fx:0.5, fy:0.5, \n"
"    stop:0 rgba(32, 86, 146, 255), stop:1 rgba(24, 53, 107, 255));\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgba(255, 255, 255, 0.3);\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    color: #a3a3a3;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(191, 171))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:1.2, \n"
"    fx:0.5, fy:0.5, \n"
"    stop:0 rgba(24, 53, 107, 255), stop:1 rgba(32, 86, 146, 255));\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    color: #ffffff;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 8px 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:1.2, \n"
"    fx:0.5, fy:0.5, \n"
"    stop:0 rgba(32, 86, 146, 255), stop:1 rgba(24, 53, 107, 255));\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgba(255, 255, 255, 0.3);\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    color: #a3a3a3;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(191, 171))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:1.2, \n"
"    fx:0.5, fy:0.5, \n"
"    stop:0 rgba(24, 53, 107, 255), stop:1 rgba(32, 86, 146, 255));\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    color: #ffffff;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 8px 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:1.2, \n"
"    fx:0.5, fy:0.5, \n"
"    stop:0 rgba(32, 86, 146, 255), stop:1 rgba(24, 53, 107, 255));\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgba(255, 255, 255, 0.3);\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    color: #a3a3a3;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "返回"))
        self.pushButton.setText(_translate("MainWindow", "读取标签"))
        self.pushButton_2.setText(_translate("MainWindow", "转换标签顺序"))
        self.pushButton_3.setText(_translate("MainWindow", "批量解压NII.GZ"))
